name: Firsat Botu Calistirici

on:
  schedule:
    - cron: '0 * * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Kodu Klonla
        uses: actions/checkout@v3

      - name: Python Kur
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Kütüphaneleri ve Tarayıcıyı Yukle
        run: |
          pip install requests playwright playwright-stealth
          playwright install chromium --with-deps

      - name: Botu Calistir
        env:
          X_USERNAME: ${{ secrets.X_USERNAME }}
          X_PASSWORD: ${{ secrets.X_PASSWORD }}
          X_EMAIL: ${{ secrets.X_EMAIL }}
        run: python bot.py
